### ISSUE TITLE
improvement request

### ISSUE THREAD

**Issue by niccolobusato** [N-l1/lovelace-soft-ui#4]
hi, your work is amazing but is kinda difficult to restart from scratch to get a new nice ui..

i was thinking about implementing this look on a theme, do you think that is possible? 

would be really nice and very convinient

**Comment by N-l1** [comment]
Yes, that would definitely be much better. Although you can specify shadows and border-radius inside an HA theme, the shadows will get cut off. That's why margins are needed, but currently, the HA theme does not support margins. 

However, card-mod "had" this feature for styling inside themes. It does not currently work, and [no one had yet confirmed if it is still working](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/544)...

For now, the simplest way of implementing this would be adding the following styling to every card:

```
style: |
  ha-card {
      background-color: var(--primary-background-color);
      border-radius: 15px;
      margin: 20px;
      box-shadow: 
           {% if is_state('sun.sun', 'above_horizon') %}
               -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
           {% else %}
               -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
           {% endif %}   
   }
```

**Comment by niccolobusato** [comment]
that's amazing. on white background the affect it's amazing!

nice work mate :)

**Comment by N-l1** [comment]
Hi @niccolobusato! 

I just tested out card-mod's [beta feature](https://github.com/thomasloven/lovelace-card-mod/blob/beta-themes/card-mod-themes.md) of styling inside a theme and it works! This means you can now add the style I gave above into your theme using the card-mod beta feature and it should universally style! As soon as the feature gets out of beta, I'll see if I can make a theme that is downloadable in HACS. Closing this issue for now.

Cheers mate 👍
